version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dash-postgres
    environment:
      POSTGRES_DB: dashdb
      POSTGRES_USER: dashuser
      POSTGRES_PASSWORD: dashpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashuser -d dashdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash-app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://dashuser:dashpass@postgres:5432/dashdb
      SESSION_SECRET: your-secret-session-key-change-this-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: dash-network